apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  description: test-project
  sourceRepos:
  - '*'
  destinations:
  - namespace: 'test'
    server: https://kubernetes.default.svc

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true