apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: projects
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/aminrj/argocd-infra.git
    targetRevision: HEAD
    path: projects
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true