apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
    - repoURL: https://github.com/argoproj/argoproj-deployments
      targetRevision: HEAD
      path: argocd/overlays/production
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true