apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-application
  namespace: test
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    kustomize: {}
    repoURL: https://github.com/aminrj/homelabs-gitops.git
    path: apps/test-application/base
    targetRevision: HEAD
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: test

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true